project_id = "ebzvluscnbkolzbqajcl"

[functions.fetch-bills]
verify_jwt = false

[functions.get-bills]
verify_jwt = false

[functions.trigger-fetch]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false